import localFont from "next/font/local";
import "./globals.css";

const avertaRegular = localFont({
  variable: "--font-averta-regular",
  src: "./fonts/AvertaRegular.woff2",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${avertaRegular.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
